DROP TABLE IF EXISTS product_tag;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE categories (
                            id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL,
                            CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE customers (
                          id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name  VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          CONSTRAINT uk_customers_email UNIQUE (email)
);

CREATE TABLE tags (
                      id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      CONSTRAINT uk_tags_name UNIQUE (name)
);

CREATE TABLE products (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name        VARCHAR(255) NOT NULL,
                          price       DECIMAL(12,2) NOT NULL,
                          stock       INTEGER NOT NULL,
                          category_id BIGINT NOT NULL,
                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE orders (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at  TIMESTAMP NOT NULL,
                        status      VARCHAR(50) NOT NULL,
                        total       DECIMAL(12,2) NOT NULL,
                        customer_id BIGINT NOT NULL,
                        CONSTRAINT fk_orders_customer
                            FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE order_lines (
                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             quantity   INTEGER NOT NULL,
                             unit_price DECIMAL(12,2) NOT NULL,
                             subtotal   DECIMAL(12,2) NOT NULL,
                             order_id   BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             CONSTRAINT fk_order_lines_order
                                 FOREIGN KEY (order_id) REFERENCES orders (id),
                             CONSTRAINT fk_order_lines_product
                                 FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE product_tag (
                             product_id BIGINT NOT NULL,
                             tag_id     BIGINT NOT NULL,
                             CONSTRAINT pk_product_tag PRIMARY KEY (product_id, tag_id),
                             CONSTRAINT fk_product_tag_product
                                 FOREIGN KEY (product_id) REFERENCES products (id),
                             CONSTRAINT fk_product_tag_tag
                                 FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role     VARCHAR(50) NOT NULL,
                       CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_products_category_id    ON products (category_id);
CREATE INDEX idx_orders_customer_id      ON orders (customer_id);
CREATE INDEX idx_order_lines_order_id    ON order_lines (order_id);
CREATE INDEX idx_order_lines_product_id  ON order_lines (product_id);
